import 'package:quest_up/features/quests/data/models/quest_model.dart';
import 'package:quest_up/features/quests/domain/entities/quest.dart';

abstract class IActivityQuestCatalogService {
  List<QuestModel> getActivityQuests();
}

class ActivityQuestCatalogService implements IActivityQuestCatalogService {
  @override
  List<QuestModel> getActivityQuests() {
    return [
      // 🌸 PHOTO & NATURE OBJECT QUESTS
      const QuestModel(
        id: 'quest_act_nature_flower',
        title: 'Find and Photograph a Flower',
        description: 'Spot a blossoming flower in a garden, plant pot, or nature trail and snap a fresh photo.',
        storyline: 'Nature blooms with vibrant floral life. Locate a fresh flower in your surroundings.',
        category: QuestCategory.nature,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.repeatable,
        latitude: 0,
        longitude: 0,
        locationName: 'Garden or Trail',
        radiusMeters: 0,
        xpReward: 40,
        coinReward: 20,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'flower',
        imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80',
        iconKey: 'nature',
        requirements: [
          QuestRequirementModel(
            title: 'Fresh In-App Photo',
            description: 'Snap a live photo of a flower using the Quest camera',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),
      const QuestModel(
        id: 'quest_act_nature_tree',
        title: 'Find and Photograph a Tree',
        description: 'Locate a tall or ancient tree in your area and capture a clear live photo.',
        storyline: 'Trees are the silent guardians of our ecosystem. Find and photograph one.',
        category: QuestCategory.nature,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.repeatable,
        latitude: 0,
        longitude: 0,
        locationName: 'Park or Green Area',
        radiusMeters: 0,
        xpReward: 40,
        coinReward: 20,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'tree',
        imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80',
        iconKey: 'nature',
        requirements: [
          QuestRequirementModel(
            title: 'Live Tree Photo',
            description: 'Snap a live in-app photo of any tree',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),
      const QuestModel(
        id: 'quest_act_nature_cow',
        title: 'Find a Cow and Take a Photo',
        description: 'Observe a cow or cattle in a pasture, farm, or countryside lane and snap a live photo.',
        storyline: 'Domestic animals are a vital part of rural and agricultural exploration. Spot a cow.',
        category: QuestCategory.nature,
        difficulty: QuestDifficulty.medium,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.repeatable,
        latitude: 0,
        longitude: 0,
        locationName: 'Farm or Rural Path',
        radiusMeters: 0,
        xpReward: 50,
        coinReward: 25,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'cow',
        imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=800&q=80',
        iconKey: 'nature',
        requirements: [
          QuestRequirementModel(
            title: 'Live Cow Photo',
            description: 'Capture a photo of a cow using the Quest camera',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),

      // 🍎 FOOD & NUTRITION QUESTS
      const QuestModel(
        id: 'quest_act_food_apple',
        title: 'Photograph an Apple',
        description: 'Find a fresh apple, fruit basket, or grocery stall and snap a live verification photo.',
        storyline: 'Fresh fruit provides healthy nutrition for active adventurers.',
        category: QuestCategory.food,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Kitchen or Market',
        radiusMeters: 0,
        xpReward: 35,
        coinReward: 15,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'apple',
        imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
        iconKey: 'food',
        requirements: [
          QuestRequirementModel(
            title: 'Apple Photo Proof',
            description: 'Snap a clear live photo of an apple',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),
      const QuestModel(
        id: 'quest_act_food_meal',
        title: 'Photograph Your Meal',
        description: 'Enjoy a nutritious balanced meal and snap a live in-app photo before eating.',
        storyline: 'Adventurers thrive on balanced fuel. Record your healthy meal.',
        category: QuestCategory.food,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Dining Table',
        radiusMeters: 0,
        xpReward: 40,
        coinReward: 20,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'food',
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        iconKey: 'food',
        requirements: [
          QuestRequirementModel(
            title: 'Meal Photo Proof',
            description: 'Capture a live photo of your meal',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),

      // 📚 STUDY & READING QUESTS
      const QuestModel(
        id: 'quest_act_study_book',
        title: 'Photograph a Book',
        description: 'Find a physical book or novel in your library or desk and capture a photo.',
        storyline: 'Books contain the cumulative knowledge of human civilization.',
        category: QuestCategory.study,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Study Desk or Library',
        radiusMeters: 0,
        xpReward: 35,
        coinReward: 15,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'book',
        imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
        iconKey: 'study',
        requirements: [
          QuestRequirementModel(
            title: 'Book Photo Proof',
            description: 'Snap a live photo of a physical book',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),
      const QuestModel(
        id: 'quest_act_reading_10m',
        title: 'Read for 10 Minutes',
        description: 'Immerse yourself in any book continuously for at least 10 minutes.',
        storyline: 'Sharpen your mind and broaden your perspective by dedicating focused time to reading.',
        category: QuestCategory.reading,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.timedVideo,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Quiet Reading Nook',
        radiusMeters: 0,
        xpReward: 50,
        coinReward: 25,
        requiredLevel: 1,
        requiredDurationSeconds: 600, // 10 minutes
        requiresVideo: true,
        imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
        iconKey: 'reading',
        requirements: [
          QuestRequirementModel(
            title: '10-Minute Reading Session',
            description: 'Record or track your reading session for at least 10:00 minutes',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),

      // ✍️ WRITING QUESTS
      const QuestModel(
        id: 'quest_act_writing_hometown',
        title: 'Write 100 Words on Your Hometown',
        description: 'Write at least 100 words describing the sights, culture, or favorite memories of your hometown.',
        storyline: 'Every traveler carries memories of home. Articulate the unique essence of your roots.',
        category: QuestCategory.writing,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.writingText,
        repeatability: QuestRepeatability.weekly,
        latitude: 0,
        longitude: 0,
        locationName: 'In-App Text Editor',
        radiusMeters: 0,
        xpReward: 40,
        coinReward: 20,
        requiredLevel: 1,
        requiredWords: 100,
        requiresText: true,
        imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
        iconKey: 'writing',
        requirements: [
          QuestRequirementModel(
            title: 'Write 100+ Words',
            description: 'Compose 100 or more words directly in the in-app writer',
            requiresGpsLocation: false,
            requiresCameraProof: false,
          ),
        ],
      ),

      // 🎨 DRAWING QUESTS
      const QuestModel(
        id: 'quest_act_draw_tree',
        title: 'Draw a Tree on Canvas',
        description: 'Open the in-app drawing canvas and illustrate a tree with branches and leaves.',
        storyline: 'Trees represent life and endurance. Express your artistic creativity.',
        category: QuestCategory.drawing,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.drawingCanvas,
        repeatability: QuestRepeatability.repeatable,
        latitude: 0,
        longitude: 0,
        locationName: 'In-App Drawing Canvas',
        radiusMeters: 0,
        xpReward: 50,
        coinReward: 25,
        requiredLevel: 1,
        requiresDrawing: true,
        requiredDrawingSubject: 'tree',
        imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
        iconKey: 'drawing',
        requirements: [
          QuestRequirementModel(
            title: 'In-App Drawing Canvas',
            description: 'Draw a tree illustration on the drawing canvas',
            requiresGpsLocation: false,
            requiresCameraProof: false,
          ),
        ],
      ),

      // 🏃 EXERCISE QUESTS
      const QuestModel(
        id: 'quest_act_exercise_10m',
        title: 'Exercise for 10 Minutes',
        description: 'Perform 10 continuous minutes of cardio, calisthenics, or bodyweight exercises.',
        storyline: 'Physical movement boosts vitality and builds strong adventurer endurance.',
        category: QuestCategory.exercise,
        difficulty: QuestDifficulty.medium,
        verificationType: QuestVerificationType.timedVideo,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Fitness Arena or Home',
        radiusMeters: 0,
        xpReward: 60,
        coinReward: 30,
        requiredLevel: 1,
        requiredDurationSeconds: 600, // 10 mins
        requiresVideo: true,
        imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
        iconKey: 'exercise',
        requirements: [
          QuestRequirementModel(
            title: '10-Minute Exercise Session',
            description: 'Complete a continuous 10-minute workout session',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),

      // 🚶 WALKING & COMPOSITE QUESTS
      const QuestModel(
        id: 'quest_act_walk_1km',
        title: 'Walk 1.0 Kilometer Outdoors',
        description: 'Step outside and walk at least 1.0 kilometer tracked live via your device GPS.',
        storyline: 'A journey of a thousand miles begins with a single kilometer.',
        category: QuestCategory.walking,
        difficulty: QuestDifficulty.medium,
        verificationType: QuestVerificationType.walkingGps,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Outdoor Walking Track',
        radiusMeters: 0,
        xpReward: 50,
        coinReward: 25,
        requiredLevel: 1,
        requiredDistanceMeters: 1000, // 1 km
        requiresGPS: true,
        imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80',
        iconKey: 'walking',
        requirements: [
          QuestRequirementModel(
            title: 'GPS Walk 1,000m',
            description: 'Accumulate 1.0 km of outdoor walking tracked via GPS',
            requiresGpsLocation: true,
            requiresCameraProof: false,
          ),
        ],
      ),
      const QuestModel(
        id: 'quest_act_walk_500m_tree',
        title: 'Walk 500m & Photograph a Tree',
        description: 'Walk 500 meters outdoors and capture a fresh photo of a tree along the path.',
        storyline: 'Combine physical movement with environmental observation on your route.',
        category: QuestCategory.walking,
        difficulty: QuestDifficulty.medium,
        verificationType: QuestVerificationType.walkingGps,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Green Pathway',
        radiusMeters: 0,
        xpReward: 65,
        coinReward: 35,
        requiredLevel: 1,
        requiredDistanceMeters: 500, // 500m
        requiresGPS: true,
        requiresFreshPhoto: true,
        requiredObject: 'tree',
        imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
        iconKey: 'walking',
        requirements: [
          QuestRequirementModel(
            title: 'GPS Walk 500m',
            description: 'Walk 500 meters tracked live via GPS',
            requiresGpsLocation: true,
            requiresCameraProof: false,
          ),
          QuestRequirementModel(
            title: 'Live Tree Photo',
            description: 'Capture a fresh photo of a tree',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),

      // 🎮 GAMING QUESTS
      const QuestModel(
        id: 'quest_act_game_puzzle_5m',
        title: 'Play Quest Puzzle for 5 Minutes',
        description: 'Play the in-app Quest Tile Adventure puzzle for at least 5 minutes.',
        storyline: 'Exercise problem-solving and spatial coordination through interactive in-app puzzle challenges.',
        category: QuestCategory.gaming,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.gameplayTime,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'In-App Game Hub',
        radiusMeters: 0,
        xpReward: 45,
        coinReward: 25,
        requiredLevel: 1,
        requiredDurationSeconds: 300, // 5 mins
        requiresGameSession: true,
        imageUrl: 'https://images.unsplash.com/photo-1612287233202-09419b48c414?auto=format&fit=crop&w=800&q=80',
        iconKey: 'gaming',
        requirements: [
          QuestRequirementModel(
            title: '5 Minutes Gameplay',
            description: 'Interact with the in-app puzzle game for 5:00 active minutes',
            requiresGpsLocation: false,
            requiresCameraProof: false,
          ),
        ],
      ),

      // 🔎 OBSERVATION QUESTS
      const QuestModel(
        id: 'quest_act_obs_bicycle',
        title: 'Find a Bicycle and Take a Photo',
        description: 'Spot a bicycle parked or riding on a street, park, or stand and snap a photo.',
        storyline: 'Spot eco-friendly two-wheeled transportation during your neighborhood exploration.',
        category: QuestCategory.observation,
        difficulty: QuestDifficulty.easy,
        verificationType: QuestVerificationType.photoProof,
        repeatability: QuestRepeatability.daily,
        latitude: 0,
        longitude: 0,
        locationName: 'Public Street or Stand',
        radiusMeters: 0,
        xpReward: 40,
        coinReward: 20,
        requiredLevel: 1,
        requiresFreshPhoto: true,
        requiredObject: 'bicycle',
        imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80',
        iconKey: 'observation',
        requirements: [
          QuestRequirementModel(
            title: 'Bicycle Photo Proof',
            description: 'Snap a live photo of a bicycle using the Quest camera',
            requiresGpsLocation: false,
            requiresCameraProof: true,
          ),
        ],
      ),
    ];
  }
}
