import 'package:quest_up/features/quests/domain/entities/quest.dart';
import 'package:quest_up/features/verification/domain/entities/quest_attempt.dart';
import 'package:quest_up/features/verification/domain/entities/validator_result.dart';
import 'i_validator.dart';

class AntiCheatWritingVerifier implements IQuestValidator {
  @override
  String get validatorName => 'Originality & Anti-Cheat';

  static final List<RegExp> _aiPatterns = [
    RegExp(r'\bas an ai\b', caseSensitive: false),
    RegExp(r'\bas a language model\b', caseSensitive: false),
    RegExp(r'\bi do not have personal (feelings|experiences|hometown)\b', caseSensitive: false),
    RegExp(r'\bhere is a (\d+[\s-]word|summary|short essay)\b', caseSensitive: false),
    RegExp(r'\bas requested,?\s+(here is|below is)\b', caseSensitive: false),
    RegExp(r'\bgenerated by ai\b', caseSensitive: false),
    RegExp(r'\bgenerated by chatgpt\b', caseSensitive: false),
  ];

  @override
  Future<ValidatorResult> validate({
    required Quest quest,
    required QuestAttempt attempt,
    required VerificationProofPayload payload,
  }) async {
    final text = payload.textContent?.trim() ?? '';
    if (text.isEmpty) {
      return const ValidatorResult(
        passed: false,
        validatorName: 'Originality & Anti-Cheat',
        actualValue: 'Empty response',
        requiredValue: 'Written text response',
        message: 'No text content provided to verify.',
      );
    }

    // 1. External Paste & Copy-Paste Detection
    if (payload.isPasted == true && payload.isAuthenticallyTyped == false) {
      return ValidatorResult(
        passed: false,
        validatorName: 'Originality & Anti-Cheat',
        actualValue: '${payload.pastedCharactersCount ?? text.length} pasted characters',
        requiredValue: '0 pasted characters (100% typed)',
        message: 'Anti-Cheat Alert: Pasted text detected from an external app. Quests must be typed genuinely in the QuestUP editor to prevent copying from ChatGPT or web sources.',
      );
    }

    // 2. AI Chatbot Signature & Pattern Detection
    final lowerText = text.toLowerCase();
    for (final pattern in _aiPatterns) {
      if (pattern.hasMatch(lowerText)) {
        return const ValidatorResult(
          passed: false,
          validatorName: 'Originality & Anti-Cheat',
          actualValue: 'AI assistant signature detected',
          requiredValue: 'Human original thoughts',
          message: 'AI Content Detected: Submission contains AI assistant phrases. Please write your own original description.',
        );
      }
    }

    // 3. Spam & Extreme Repetition Heuristic (Preventing "a a a" 100 times)
    final words = text.split(RegExp(r'\s+')).where((w) => w.isNotEmpty).map((w) => w.toLowerCase()).toList();
    if (words.length >= 20) {
      final uniqueWords = words.toSet();
      final diversityRatio = uniqueWords.length / words.length;
      if (diversityRatio < 0.15) {
        return ValidatorResult(
          passed: false,
          validatorName: 'Originality & Anti-Cheat',
          actualValue: '${(diversityRatio * 100).toStringAsFixed(0)}% unique words',
          requiredValue: '> 15% unique words',
          message: 'Repetitive Spam Detected: Please write meaningful sentences rather than repeating the same words.',
        );
      }
    }

    return const ValidatorResult(
      passed: true,
      validatorName: 'Originality & Anti-Cheat',
      actualValue: 'Authentic composition',
      requiredValue: 'Authentic writing',
      message: 'Originality Check Passed: Genuine response verified.',
    );
  }
}
